In [52]:
import numpy as np
import random

def FA(z):
      if z > 0:
            return 1
      elif z < 0:
            return -1
      else:
            return 0

def recursion(x1, P1, max_recursiones = 15, num_llamadas = 1):
      if num_llamadas >= max_recursiones:
            print("Número máximo de recursiones alcanzado para esta entrada")
            return num_llamadas
      z1 = np.dot(x1, P1)
      print("z1: ", z1)      
      r1 = np.array([FA(z1[i]) for i in range(len(z1))])
      print("r1: ", r1)
      
      # Si el vector resultante “R_1” es igual a “en este caso x1” entonces se evalúa la
      # siguiente entrada,
      if np.array_equal(r1, x1):
            print("El vector R y la entreda X son iguales")
            #z2 = np.dot(x2, P1)
            #print("z2: ", z2)
            return num_llamadas
      # de lo contrario R_1 se multiplica nuevamente por los pesos,
      # resultando R_2, si R_2 = R_1 entonces se pasa a la siguiente entrada y se realiza un
      # proceso similar a partir del paso e,
      
      r2 = r1
      while num_llamadas < max_recursiones:
            aux = r2
            # de lo contrario se continúan multiplicando los
            # pesos hasta hallar similitud con la entrada R_n.
            r2 = np.array([FA(np.dot(r2, P1)[i]) for i in range(len(r2))])
            print("r2: ", r2)
            num_llamadas += 1
                  
            if np.array_equal(r2, aux):
                  print("Recursion -> ", r2)
                  return recursion(r2, P1, max_recursiones, num_llamadas)
            elif np.array_equal(r2, x1):
                  print("x1 = x2 -> ", r2)
                  return num_llamadas
            else:
                  aux = r2
                  print("Siguiente...")

      
            if num_llamadas >= max_recursiones:
                  print("Número máximo de recursiones alcanzado para esta entrada")
                  return
      print("Número máximo de recursiones alcanzado para esta entrada")
      return num_llamadas


def hopfield(x, cantidad_vectores, tamanio_vector):
      M = []
      for i in range(cantidad_vectores):
            M.append(np.outer(x[i], x[i]))
    
      P = np.zeros(tamanio_vector, dtype=int)

      for i in range(cantidad_vectores):
            P = sum(M)
      print("Matriz de pesos obtenidos")
      print(P)
      print("\n")

      for i in range(tamanio_vector):
            for j in range(tamanio_vector):
                  if i == j:
                        P[i][j]=0
      print("Matriz de pesos obtenidos con diagonal 0")
      print(P)

      for i in range(cantidad_vectores):
            print(f"\nEntada numero {i+1}")
            print(f"x({i}) : ",x[i])
            llamadas = recursion(x[i],P)
            print(f"Cantidad de llamadas realizadas para la entrada {i+1}: {llamadas}")


In [53]:
values = [1, -1]
inputs = []


while True:
    cantidad_vectores = input("Cantidad de vectores (entre 3 y 5): ")
    if cantidad_vectores.isdigit() and 3 <= int(cantidad_vectores) <= 5:
        break
    else:
        print("Por favor, ingresa un número entre 3 y 5.")

tamanio_vector = input(f"Tamaño de los vectores: ")
for i in range(int(cantidad_vectores)):
    x = np.zeros(int(tamanio_vector), dtype=int)
    for j in range(int(tamanio_vector)):
            x[j] = random.choice(values)
    print(f"Vector obtenido {i +1}: ",x)
    inputs.append(x.copy())


hopfield(inputs, int(cantidad_vectores), int( tamanio_vector))

Vector obtenido 1:  [-1 -1  1  1  1  1 -1 -1  1  1 -1 -1 -1  1  1]
Vector obtenido 2:  [-1 -1  1 -1  1  1 -1  1 -1  1 -1  1  1  1  1]
Vector obtenido 3:  [-1  1 -1  1  1  1  1 -1  1 -1  1  1 -1 -1  1]
Vector obtenido 4:  [ 1  1 -1 -1  1 -1  1  1  1 -1  1  1 -1  1 -1]
Vector obtenido 5:  [-1  1  1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1  1]
[[ 5  1 -3 -1 -1 -3  1  3 -1 -3  3  1  1 -1 -5]
 [ 1  5 -3 -1 -1 -3  5 -1  3 -3  3  1 -3 -1 -1]
 [-3 -3  5 -1 -1  1 -3 -1 -1  5 -5 -3  1  3  3]
 [-1 -1 -1  5  1  3 -1 -3  1 -1  1 -1 -1 -3  1]
 [-1 -1 -1  1  5  3 -1  1  1 -1  1  3 -1  1  1]
 [-3 -3  1  3  3  5 -3 -1 -1  1 -1  1  1 -1  3]
 [ 1  5 -3 -1 -1 -3  5 -1  3 -3  3  1 -3 -1 -1]
 [ 3 -1 -1 -3  1 -1 -1  5 -3 -1  1  3  3  1 -3]
 [-1  3 -1  1  1 -1  3 -3  5 -1  1 -1 -5  1  1]
 [-3 -3  5 -1 -1  1 -3 -1 -1  5 -5 -3  1  3  3]
 [ 3  3 -5  1  1 -1  3  1  1 -5  5  3 -1 -3 -3]
 [ 1  1 -3 -1  3  1  1  3 -1 -3  3  5  1 -1 -1]
 [ 1 -3  1 -1 -1  1 -3  3 -5  1 -1  1  5 -1 -1]
 [-1 -1  3 -3  1 -1 -1  1  1  3 -3 -1 -1 