In [54]:
import numpy as np
import random
# Convierte la matriz resultante cambiando los números de la diagonal por 0s (esta
# será P_1).
def obtencionP(P1):
    for i in range(N):
        for j in range(N):
            if i == j:
                P1[j][i]=0
    print("P1")
    print(P1)
    return P1

def FA(z):
      if z > 0:
            return 1
      elif z < 0:
            return -1
      else:
            return 0

def recursion(x1, P1, max_recursiones = 15, num_llamadas = 0):
      if num_llamadas >= max_recursiones:
            print("Número máximo de recursiones alcanzado para esta entrada")
            return
      z1 = np.dot(x1, P1)
      print("z1: ", z1)      
      r1 = np.array([FA(z1[i]) for i in range(len(z1))])
      print("r1: ", r1)
      
      # Si el vector resultante “R_1” es igual a “en este caso x1” entonces se evalúa la
      # siguiente entrada,
      if np.array_equal(r1, x1):
            print("El vector Z y la entreda X son iguales")
            #z2 = np.dot(x2, P1)
            #print("z2: ", z2)
            return
      # de lo contrario R_1 se multiplica nuevamente por los pesos,
      # resultando R_2, si R_2 = R_1 entonces se pasa a la siguiente entrada y se realiza un
      # proceso similar a partir del paso e,
      
      r2 = r1
      while num_llamadas < max_recursiones:
            aux = r2
            # de lo contrario se continúan multiplicando los
            # pesos hasta hallar similitud con la entrada R_n.
            r2 = np.array([FA(np.dot(r2, P1)[i]) for i in range(len(r2))])
            print("r2: ", r2)
                  
            if np.array_equal(r2, aux):
                  print("Recursion -> ", r2)
                  recursion(r2,P1)
                  return
            elif np.array_equal(r2, x1):
                  print("x1 = x2 -> ", r2)
                  return
            else:
                  aux = r2
                  print("Siguiente...")

            num_llamadas += 1
            if num_llamadas >= max_recursiones:
                  print("Número máximo de recursiones alcanzado para esta entrada")
                  return
      print("Número máximo de recursiones alcanzado para esta entrada")



def funcionPrincipal(x1, x2):
      # Realiza una multiplicación de cada vector por su transpuesta de este, para obtener
      # dos matrices de NxN.
    M1 = np.outer(x1, x1)
    M2 = np.outer(x2, x2)

    print("M1: \n", M1)
    print("M2: \n", M2)
    # Las matrices resultantes serán sumadas (considera que estas deben ser del mismo
    # tamaño), estos representarán los pesos de la red neuronal.
    P1 = M1 + M2

    P1 = obtencionP(P1)
    print("\n Primera entrada\n")
    recursion(x1, P1)
    print("\n Siguientre entrada\n")
    recursion(x2, P1)

In [55]:
# Considerar 2 (x1 y x2) entradas de vectores del mismo tamaño, toma en cuenta que
# pueden ser 1 y -1 los valores de la matriz solamente. Estos se ingresarán de manera
# manual y puede variar el tamaño del par de vectores.

values = [1, -1]
N = 3
x1 = np.zeros(N, dtype=int)
x2 = np.zeros(N, dtype=int)

for i in range(N):
    x1[i] = random.choice(values)
    x2[i] = random.choice(values)

print("x1:", x1)
print("x2:", x2)


funcionPrincipal(x1,x2)

x1: [-1  1  1]
x2: [1 1 1]
M1: 
 [[ 1 -1 -1]
 [-1  1  1]
 [-1  1  1]]
M2: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
P1
[[0 0 0]
 [0 0 2]
 [0 2 0]]

 Primera entrada

z1:  [0 2 2]
r1:  [0 1 1]
r2:  [0 1 1]
Recursion ->  [0 1 1]
z1:  [0 2 2]
r1:  [0 1 1]
El vector Z y la entreda X son iguales

 Siguientre entrada

z1:  [0 2 2]
r1:  [0 1 1]
r2:  [0 1 1]
Recursion ->  [0 1 1]
z1:  [0 2 2]
r1:  [0 1 1]
El vector Z y la entreda X son iguales
