In [37]:
import numpy as np
import random

values = [1, -1]
N = 4
n = 2

inputs = []

for i in range(n):
    x = np.zeros(N, dtype=int)
    for j in range(N):
        x[j] = random.choice(values)
    inputs.append(x.copy())

print(inputs)


[array([-1,  1,  1, -1]), array([ 1, -1,  1, -1])]


In [ ]:
def FA(z):
      if z > 0:
            return 1
      elif z < 0:
            return -1
      else:
            return 0

def recursion(x1, P1):
      z1 = np.dot(x1, P1)
      print("z1: ", z1)
      
      r1 = np.array([FA(z1[i]) for i in range(len(z1))])
      print("r1: ", r1)
      
      # Si el vector resultante “R_1” es igual a “en este caso x1” entonces se evalúa la
      # siguiente entrada,
      if np.array_equal(r1, x1):
            z2 = np.dot(x2, P1)
            print("z2: ", z2)
            return
      # de lo contrario R_1 se multiplica nuevamente por los pesos,
      # resultando R_2, si R_2 = R_1 entonces se pasa a la siguiente entrada y se realiza un
      # proceso similar a partir del paso e,
      else:
            r2 = r1
            while True:
                  aux = r2
                  # de lo contrario se continúan multiplicando los
                  # pesos hasta hallar similitud con la entrada R_n.
                  r2 = np.array([FA(np.dot(r2, P1)[i]) for i in range(len(r2))])
                  print("r2: ", r2)
                  
                  if np.array_equal(r2, aux):
                        print("Recursion -> ", r2)
                        return
                  elif np.array_equal(r2, x1):
                        print("x1 = x2 -> ", r2)
                        return
                  else:
                        aux = r2
                        print("Siguiente...")

In [38]:
def hopfield(x, n, N):
    M = []

    for i in range(n):
        M.append(np.outer(x[i], x[i]))
    
    print(M)

    P = np.zeros(N, dtype=int)

    for i in range(n):
        P = sum(M)
    
    print(P)

    for i in range(N):
        for j in range(N):
            if i == j:
                P[i][j]=0

    print(P)

    for i in range(n):
        recursion()



hopfield(inputs, n, N)

[array([[ 1, -1, -1,  1],
       [-1,  1,  1, -1],
       [-1,  1,  1, -1],
       [ 1, -1, -1,  1]]), array([[ 1, -1,  1, -1],
       [-1,  1, -1,  1],
       [ 1, -1,  1, -1],
       [-1,  1, -1,  1]])]
[[ 2 -2  0  0]
 [-2  2  0  0]
 [ 0  0  2 -2]
 [ 0  0 -2  2]]
